### ISSUE TITLE
Umsatz Activity - Absturz bei keiner Internetverbindung

### ISSUE THREAD

**Issue by Fabi755** [jtuttas/mmbbsapp#1]
Ruft man im Menü die Umsatzanzeige ohne Internetverbindung auf, stürzt die App.

Ablauf:
- Internet ausstellen
- App starten
- Menü öffnen
- Option "Umsatz" auswählen

Gerät:
- Samsung Galaxy S3
- Version: Android 4.3

**Comment by jtuttas** [comment]
Sollte mit dem heutigen Update behoben sein !

Gruß

Jörg Tuttas
