### ISSUE TITLE
Informationen zur Klasse nicht gefunden

### ISSUE THREAD

**Issue by Fabi755** [jtuttas/mmbbsapp#2]
Informationen zur Klasse werden beim Aufruf von Stundenplan/Vertretungsplan nicht gefunden.

Nachstellung:
1. App öffnen
2. Einstellungen auswählen
3. "FIAE13G" als Klassenbezeichnung auswählen
4. Zur Startseite zurückkehren
5. Meine Klasse auswählen
6. Stundenplan oder Vertretungsplan auswählen

**Comment by jtuttas** [comment]
Hallo, nach dem Starten der App die Menü Taste drücken und "update DB" machen (und langsam bis drei zählen :-), dann sollte es wieder gehen !
