### ISSUE TITLE
Installation auf Android L durch falsche Permissions unmöglich

### ISSUE THREAD

**Issue by Manawyrm** [jtuttas/mmbbsapp#3]
Hallo,

die MMBBS App beißt sich aktuell mit anderen Android Apps. 
Ein gutes Beispiel ist dafür die App "HABDroid". Es kann immer nur entweder die MMBBS oder die HABDroid App installiert werden. 

Beim HABdroid Projekt ist hierzu schon eine Issue offen, 
https://github.com/openhab/openhab.android/issues/32
es geht hierbei wohl darum, dass die Permissions im Manifest mit "com.example" definiert wurden und daher doppelt vorhanden sind.

Bei der Installation aus dem PlayStore erscheint daher die Fehlermeldung -505, im LogCat des Handys erscheint folgende Logmeldung:

`E/Finsky  ( 2476): [1] PackageInstallerImpl.handleCommitCallback: Error -505 while installing org.openhab.habdroid: INSTALL_FAILED_DUPLICATE_PERMISSION: Package org.openhab.habdroid attempting to redeclare permission com.example.gcm.permission.C2D_MESSAGE already owned by de.mmbbs`

**Comment by jtuttas** [comment]
Hallo Herr Mädel, 
Danke für den Hinweis, ich werde das im kommenden Release berücksichtigen. 

Gruß und schönes Wochenende 

Jörg Tuttas 
Jörg Tuttas 
Ellernbuschfeld 23b 
30539 Hannover 
Telefon 0511 / 80600295 

Am 5. Dezember 2014 22:23:39 MEZ, schrieb "Tobias Mädel" notifications@github.com:

**Comment by jtuttas** [comment]
Hallo Herr Mädel, so bug nunbehoben, dieses Repository wird übrigens nicht mehr weiter geführt (und irgend wann auch gelöscht), da ich nun auf Android Studio umgestiegen bin, hier geht es zum neuen Repository https://github.com/jtuttas/mmbbsapp_AndroidStudio

Gruß

Jörg Tuttas
